from .clienteSerializer import ClienteSerializer
from .userSerializer import UserSerializer
from .categoriaSerializer import CategoriaSerializer
from .servicioSerializer import ServicioSerializer
from .empleadoSerializer import EmpleadoSerializer
from .citaSerializer import CitaSerializer