# Generated by Django 4.1.1 on 2022-09-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('estado', models.CharField(default='Activo', max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Precio')),
                ('stock', models.CharField(max_length=20, verbose_name='Stock')),
                ('estado', models.CharField(default='Activo', max_length=10, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_servicios_categorias', to='authApp.categoria')),
            ],
        ),
    ]
