# Generated by Django 4.1.1 on 2022-09-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='codigo_usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='codigo_usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Cita'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Email'),
        ),
    ]
