# Generated by Django 4.1.1 on 2022-09-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_citas_empleados', to='authApp.empleado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='Agendada', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.CharField(max_length=20, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(max_length=20, verbose_name='Lugar'),
        ),
    ]
