# Generated by Django 4.1.1 on 2022-09-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.CharField(max_length=20, verbose_name='Hora'),
        ),
    ]
