# Generated by Django 4.1.1 on 2022-09-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_rename_codigo_usuario_cliente_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_codigo',
            new_name='id',
        ),
    ]
