# Generated by Django 4.1.1 on 2022-09-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_servicio_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='stock',
        ),
    ]
