# Generated by Django 4.1.1 on 2022-09-11 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_cliente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='cita_codigo',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='empleado_codigo',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL),
        ),
    ]
