# Generated by Django 4.1.1 on 2022-09-12 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_alter_cliente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='lugar_servicio',
            new_name='lugar',
        ),
    ]
